### ISSUE TITLE
[vscode] unexpected to be run on `.js` files

### ISSUE THREAD

**Issue by JounQin** [plantain-00/type-coverage#81]
![image](https://user-images.githubusercontent.com/8336744/108733094-218f7e00-7569-11eb-8bd5-0642803371f5.png)

**Comment by plantain-00** [comment]
What's your `tsconfig.json`?

**Comment by JounQin** [comment]
plain js project

**Comment by plantain-00** [comment]
The vscode plugin can be activated by js file and jsx file because of typescript supports `allowJs`: https://github.com/plantain-00/type-coverage/blob/master/packages/vscode/package.json#L37-L38 
Actually, the vscode typescript and typescript eslint plugin are also checking pure js project, so I think it's OK that this plugin is checking pure js project too.
![屏幕快照 2021-02-23 07 45 40](https://user-images.githubusercontent.com/7639395/108784923-60debe80-75ab-11eb-80d4-19f3e5af28dc.png)

**Comment by JounQin** [comment]
This is very unexpected. It should read `allowJs` of `tsconfig.json`, if there's no `tsconfig.json`, it should just ignore `.js` files IMO.

I have to uninstall it because it's very noise for `.js` files now.

> typescript eslint plugin are also checking pure js project

That's because you enabled it for `.js` explicitly in eslint config.

**Comment by plantain-00** [comment]
js file validation now is in configuration and disabled by default.
![屏幕快照 2021-02-28 12 31 17](https://user-images.githubusercontent.com/7639395/109408061-ee157f00-79c0-11eb-8821-1e31d8f2f168.png)
